feat: get secret from pvc annotation
SwissDataScienceCenter/csi-rclone pull request #20
Opened 2024-08-30 23:14 UTC by olevski

Still WIP.

2024-09-02 07:59 UTC, Panaetius requested changes
thanks, the handling of the background process looks much cleaner now!
only had two minor comments

2024-09-02 07:59 UTC, Panaetius commented on pkg/rclone/driver.go
> +	return nil
question: is this some go convention or can you just `return err` here instead of the `if` block?

2024-09-02 07:59 UTC, Panaetius commented on pkg/rclone/nodeserver.go
> +	// Regardless of whetehr the secret is passed via annotations or not we assume that the encrypted secret
```suggestion
	// Regardless of whether the secret is passed via annotations or not we assume that the encrypted secret
```

2024-09-02 08:11 UTC, olevski commented on pkg/rclone/driver.go
> +	return nil
Ah my bad I should just return err. I think I had more code in between the two statements that I removed and I forgot to fully clean up.

2024-09-03 23:11 UTC, olevski commented
This change is part of the following stack:

- #20 ◀

<sub>Change managed by [git-spice](https://abhinav.github.io/git-spice/).</sub>

2024-09-04 07:47 UTC, Panaetius approved these changes

2024-09-04 07:50 UTC, merged