fix: unmount existing rclone mounts at startup
SwissDataScienceCenter/csi-rclone pull request #41
Opened 2024-11-10 20:13 UTC by olevski

Doing the unmounting in a helm preStart hook was causing issues.

2024-11-10 20:13 UTC, olevski commented
This change is part of the following stack:

- #40
    - #41 ◀

<sub>Change managed by [git-spice](https://abhinav.github.io/git-spice/).</sub>
<!-- gs:navigation comment -->

2024-11-11 07:13 UTC, Panaetius requested changes

2024-11-11 07:13 UTC, Panaetius commented on pkg/rclone/driver.go
> +func unmountExiting() {
```suggestion
func unmountExisting() {
```

2024-11-11 07:13 UTC, Panaetius commented on pkg/rclone/driver.go
> +		klog.Warningf("Could not list mounts when trying to unmount exising mounts: %v", err)
```suggestion
		klog.Warningf("Could not list mounts when trying to unmount existing mounts: %v", err)
```

2024-11-11 15:00 UTC, Panaetius approved these changes

2024-11-11 16:26 UTC, merged